/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminCardsRouteImport } from './routes/_authenticated/admin/cards'
import { Route as AuthenticatedAdminOtpsRouteImport } from './routes/_authenticated/admin/otps'
import { Route as ApiAdminCardsRouteImport } from './routes/api/admin/cards'
import { Route as ApiPublicControlRouteImport } from './routes/api/public/control'
import { Route as ApiPublicGateRouteImport } from './routes/api/public/gate'
import { Route as ApiPublicOtpRouteImport } from './routes/api/public/otp'
import { Route as ApiPublicSessionsRouteImport } from './routes/api/public/sessions'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as AuthenticatedAdminCardsCardIdRouteImport } from './routes/_authenticated/admin/cards/$cardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCardsRoute = AuthenticatedAdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOtpsRoute = AuthenticatedAdminOtpsRouteImport.update({
  id: '/otps',
  path: '/otps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiAdminCardsRoute = ApiAdminCardsRouteImport.update({
  id: '/api/admin/cards',
  path: '/api/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicControlRoute = ApiPublicControlRouteImport.update({
  id: '/api/public/control',
  path: '/api/public/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGateRoute = ApiPublicGateRouteImport.update({
  id: '/api/public/gate',
  path: '/api/public/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtpRoute = ApiPublicOtpRouteImport.update({
  id: '/api/public/otp',
  path: '/api/public/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSessionsRoute = ApiPublicSessionsRouteImport.update({
  id: '/api/public/sessions',
  path: '/api/public/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCardsCardIdRoute =
  AuthenticatedAdminCardsCardIdRouteImport.update({
    id: '/$cardId',
    path: '/$cardId',
    getParentRoute: () => AuthenticatedAdminCardsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/cards': typeof AuthenticatedAdminCardsRouteWithChildren
  '/admin/otps': typeof AuthenticatedAdminOtpsRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/gate': typeof ApiPublicGateRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/sessions': typeof ApiPublicSessionsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/cards/$cardId': typeof AuthenticatedAdminCardsCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/cards': typeof AuthenticatedAdminCardsRouteWithChildren
  '/admin/otps': typeof AuthenticatedAdminOtpsRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/gate': typeof ApiPublicGateRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/sessions': typeof ApiPublicSessionsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/admin/cards/$cardId': typeof AuthenticatedAdminCardsCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/cards': typeof AuthenticatedAdminCardsRouteWithChildren
  '/_authenticated/admin/otps': typeof AuthenticatedAdminOtpsRoute
  '/api/admin/cards': typeof ApiAdminCardsRoute
  '/api/public/control': typeof ApiPublicControlRoute
  '/api/public/gate': typeof ApiPublicGateRoute
  '/api/public/otp': typeof ApiPublicOtpRoute
  '/api/public/sessions': typeof ApiPublicSessionsRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/_authenticated/admin/cards/$cardId': typeof AuthenticatedAdminCardsCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/cards'
    | '/admin/otps'
    | '/api/admin/cards'
    | '/api/public/control'
    | '/api/public/gate'
    | '/api/public/otp'
    | '/api/public/sessions'
    | '/api/public/track'
    | '/admin/cards/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/cards'
    | '/admin/otps'
    | '/api/admin/cards'
    | '/api/public/control'
    | '/api/public/gate'
    | '/api/public/otp'
    | '/api/public/sessions'
    | '/api/public/track'
    | '/admin/cards/$cardId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/cards'
    | '/_authenticated/admin/otps'
    | '/api/admin/cards'
    | '/api/public/control'
    | '/api/public/gate'
    | '/api/public/otp'
    | '/api/public/sessions'
    | '/api/public/track'
    | '/_authenticated/admin/cards/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAdminCardsRoute: typeof ApiAdminCardsRoute
  ApiPublicControlRoute: typeof ApiPublicControlRoute
  ApiPublicGateRoute: typeof ApiPublicGateRoute
  ApiPublicOtpRoute: typeof ApiPublicOtpRoute
  ApiPublicSessionsRoute: typeof ApiPublicSessionsRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cards': {
      id: '/_authenticated/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AuthenticatedAdminCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/otps': {
      id: '/_authenticated/admin/otps'
      path: '/otps'
      fullPath: '/admin/otps'
      preLoaderRoute: typeof AuthenticatedAdminOtpsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/admin/cards': {
      id: '/api/admin/cards'
      path: '/api/admin/cards'
      fullPath: '/api/admin/cards'
      preLoaderRoute: typeof ApiAdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/control': {
      id: '/api/public/control'
      path: '/api/public/control'
      fullPath: '/api/public/control'
      preLoaderRoute: typeof ApiPublicControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gate': {
      id: '/api/public/gate'
      path: '/api/public/gate'
      fullPath: '/api/public/gate'
      preLoaderRoute: typeof ApiPublicGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/otp': {
      id: '/api/public/otp'
      path: '/api/public/otp'
      fullPath: '/api/public/otp'
      preLoaderRoute: typeof ApiPublicOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sessions': {
      id: '/api/public/sessions'
      path: '/api/public/sessions'
      fullPath: '/api/public/sessions'
      preLoaderRoute: typeof ApiPublicSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cards/$cardId': {
      id: '/_authenticated/admin/cards/$cardId'
      path: '/$cardId'
      fullPath: '/admin/cards/$cardId'
      preLoaderRoute: typeof AuthenticatedAdminCardsCardIdRouteImport
      parentRoute: typeof AuthenticatedAdminCardsRoute
    }
  }
}

interface AuthenticatedAdminCardsRouteChildren {
  AuthenticatedAdminCardsCardIdRoute: typeof AuthenticatedAdminCardsCardIdRoute
}

const AuthenticatedAdminCardsRouteChildren: AuthenticatedAdminCardsRouteChildren =
  {
    AuthenticatedAdminCardsCardIdRoute: AuthenticatedAdminCardsCardIdRoute,
  }

const AuthenticatedAdminCardsRouteWithChildren =
  AuthenticatedAdminCardsRoute._addFileChildren(
    AuthenticatedAdminCardsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCardsRoute: typeof AuthenticatedAdminCardsRouteWithChildren
  AuthenticatedAdminOtpsRoute: typeof AuthenticatedAdminOtpsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCardsRoute: AuthenticatedAdminCardsRouteWithChildren,
  AuthenticatedAdminOtpsRoute: AuthenticatedAdminOtpsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAdminCardsRoute: ApiAdminCardsRoute,
  ApiPublicControlRoute: ApiPublicControlRoute,
  ApiPublicGateRoute: ApiPublicGateRoute,
  ApiPublicOtpRoute: ApiPublicOtpRoute,
  ApiPublicSessionsRoute: ApiPublicSessionsRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
